[ContentBrowser]
ContentBrowserTab1.SelectedPaths=/Game/TopDown

[/Script/Blutility.EditorUtilitySubsystem]
#ToolMenu scripts to run on startup
#Menu Object for the Main Menu
+StartupObjects=/Game/LevelTool/EUB_LevelEditorLabel.EUB_LevelEditorLabel
+StartupObjects=/Game/LevelTool/EUB_OpenLevelEditor.EUB_OpenLevelEditor

